# AUTO-GENERATED from _test/fixtures/people.json.
# Edit people.json and run _test/fixtures/regenerate.sh — do not edit this file.
# Sourced by provision-fixture.sh inside the running Samba DC.

set -euo pipefail

DOMAIN_DN='DC=example,DC=local'
USERS_DN='CN=Users,DC=example,DC=local'
LDB='/var/lib/samba/private/sam.ldb'

# ----- groups ----------------------------------------------------------------
samba-tool group add 'alpha' >/dev/null
samba-tool group add 'beta' >/dev/null
samba-tool group add 'Gamma Nested' >/dev/null

# ----- nested-group memberships ----------------------------------------------
samba-tool group addmembers 'beta' 'Gamma Nested' >/dev/null

# ----- named users -----------------------------------------------------------
create_user() {
    local sam="$1" given="$2" surname="$3" mail="$4" password="$5"
    samba-tool user create "$sam" "$password" \
        --given-name="$given" \
        --surname="$surname" \
        --mail-address="$mail" \
        --use-username-as-cn \
        >/dev/null
    # set displayName so ADClient::entry2User picks up the right 'name'
    ldbmodify -H "$LDB" >/dev/null <<EOF
dn: CN=${sam},${USERS_DN}
changetype: modify
replace: displayName
displayName: ${given} ${surname}
EOF
}

set_attr() {
    local sam="$1" attr="$2" value="$3"
    ldbmodify -H "$LDB" >/dev/null <<EOF
dn: CN=${sam},${USERS_DN}
changetype: modify
replace: ${attr}
${attr}: ${value}
EOF
}

create_user 'a.legrand' 'Amerigo' 'Legrand' 'a.legrand@example.com' 'Foo_b_ar123!'
set_attr 'a.legrand' mobile '+63 (483) 526-8809'
set_attr 'a.legrand' userAccountControl '66048'
create_user 'a.blaskett' 'Allene' 'Blaskett' 'a.blaskett@example.com' 'Foo_b_ar123!'
create_user 'andras.k' 'Andras' 'Kovac' 'andras.k@example.com' 'Foo_b_ar123!'
create_user 'm.albro' 'Maire' 'Albro' 'm.albro@example.com' 'Foo_b_ar123!'
create_user 'm.mcnevin' 'Mike' 'McNevin' 'm.mcnevin@example.com' 'Foo_b_ar123!'
create_user 'x.guiu' 'Xanthus' 'Guiu' 'x.guiu@example.com' 'Foo_b_ar123!'
create_user 'averylongusernamethatisverylong' 'Long' 'Username' 'long@example.com' 'Foo_b_ar123!'

# ----- named-user → group memberships ---------------------------------------
samba-tool group addmembers 'alpha' 'a.blaskett,andras.k' >/dev/null
samba-tool group addmembers 'beta' 'a.legrand' >/dev/null
samba-tool group addmembers 'Gamma Nested' 'a.legrand,m.albro,m.mcnevin' >/dev/null

# ----- padding users so count assertions pass --------------------------------
echo "Creating padding users (this takes a minute)..."
PADDING_PASS='Foo_b_ar123!'
PADDING_SN='User'
for i in $(seq 1 260); do
    sam=$(printf 'p.user%03d' "$i")
    given=$(printf 'P%d' "$i")
    samba-tool user create "$sam" "$PADDING_PASS" \
        --given-name="$given" \
        --surname="$PADDING_SN" \
        --use-username-as-cn \
        >/dev/null
    if [ "$i" -le 28 ]; then
        samba-tool group addmembers 'alpha' "$sam" >/dev/null
    fi
done
