#!/usr/bin/env python3
# Render the shared fixture spec (people.json) to a backend-specific
# provisioning artifact. One spec, two backends, two output formats.
#
#   --target openldap   →  LDIF on stdout (consumed by osixia/openldap's
#                          auto-load on first boot)
#   --target samba      →  bash script on stdout (sourced by
#                          provision-fixture.sh inside the running DC)
#
# Drift is policed by CI: regenerate.sh writes the outputs back into the
# repo and the workflow `git diff --exit-code`s them.

import argparse
import json
import re
import sys
from pathlib import Path


SPEC_PATH = Path(__file__).parent / "people.json"


# Pre-computed {SSHA}base64(sha1(pw+salt)+salt) for the cleartext
# passwords used by OpenLDAP-side users. Deterministic so the rendered
# LDIF is reproducible across machines. If you add a new OpenLDAP user
# with a new password, add its hash here.
OPENLDAP_PASSWORD_HASHES = {
    "password": "{SSHA}IVszbZ6yoe3HJWwInv8FP7QX3KnM7YvmsBS5xQ==",
}


def load_spec():
    with open(SPEC_PATH) as f:
        spec = json.load(f)
    # Strip _comment keys recursively so they don't leak into output
    return _strip_comments(spec)


def _strip_comments(obj):
    if isinstance(obj, dict):
        return {k: _strip_comments(v) for k, v in obj.items()
                if not k.startswith("_comment")}
    if isinstance(obj, list):
        return [_strip_comments(v) for v in obj]
    return obj


def for_backend(entities, backend):
    return [e for e in entities if backend in e.get("backends", [])]


# ----------------------------------------------------------------------------
# OpenLDAP / LDIF
# ----------------------------------------------------------------------------

def render_openldap(spec):
    cfg = spec["domains"]["openldap"]
    base = cfg["base"]
    people_ou = cfg["people_ou"]
    groups_ou = cfg["groups_ou"]

    users = for_backend(spec["users"], "openldap")
    groups = for_backend(spec["groups"], "openldap")

    # Invert user.memberOf into group.memberUid for posixGroup
    members_by_group = {g["name"]: [] for g in groups}
    for u in users:
        for g in u.get("memberOf", []):
            if g in members_by_group:
                members_by_group[g].append(u["uid"])

    out = []
    out.append("# AUTO-GENERATED from _test/fixtures/people.json.")
    out.append("# Edit people.json and run _test/fixtures/regenerate.sh — do not edit this file.")
    out.append("")
    out.append(f"dn: {people_ou}")
    out.append("objectClass: organizationalUnit")
    out.append(f"ou: {people_ou.split('=', 1)[1].split(',', 1)[0]}")
    out.append("")
    out.append(f"dn: {groups_ou}")
    out.append("objectClass: organizationalUnit")
    out.append(f"ou: {groups_ou.split('=', 1)[1].split(',', 1)[0]}")
    out.append("")

    for u in users:
        password = u["password"]
        if password not in OPENLDAP_PASSWORD_HASHES:
            raise SystemExit(
                f"User {u['uid']!r} uses password {password!r} which has no "
                f"pre-computed SSHA hash. Add it to OPENLDAP_PASSWORD_HASHES "
                f"in render.py.")
        out.append(f"dn: uid={u['uid']},{people_ou}")
        out.append("objectClass: inetOrgPerson")
        out.append("objectClass: posixAccount")
        out.append(f"uid: {u['uid']}")
        out.append(f"cn: {u['cn']}")
        out.append(f"sn: {u['sn']}")
        out.append(f"mail: {u['mail']}")
        out.append(f"uidNumber: {u['uidNumber']}")
        out.append(f"gidNumber: {u['gidNumber']}")
        out.append(f"homeDirectory: {u['homeDirectory']}")
        out.append(f"userPassword: {OPENLDAP_PASSWORD_HASHES[password]}")
        out.append("")

    for g in groups:
        out.append(f"dn: cn={g['name']},{groups_ou}")
        out.append("objectClass: posixGroup")
        out.append(f"cn: {g['name']}")
        out.append(f"gidNumber: {g['gid']}")
        for uid in members_by_group[g["name"]]:
            out.append(f"memberUid: {uid}")
        out.append("")

    # Drop the trailing blank line for cleaner diffs
    while out and out[-1] == "":
        out.pop()
    out.append("")
    return "\n".join(out)


# ----------------------------------------------------------------------------
# Samba AD / samba-tool bash
# ----------------------------------------------------------------------------

_VALID_BASH_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _sh_quote(s):
    # Single-quote for safety, escape embedded single quotes
    return "'" + str(s).replace("'", "'\\''") + "'"


def render_samba(spec):
    cfg = spec["domains"]["samba"]
    base = cfg["base"]
    users_dn = cfg["users_dn"]
    ldb = cfg["ldb_path"]

    users = for_backend(spec["users"], "samba")
    groups = for_backend(spec["groups"], "samba")
    padding = spec.get("padding")
    if padding and "samba" not in padding.get("backends", []):
        padding = None

    out = []
    out.append("# AUTO-GENERATED from _test/fixtures/people.json.")
    out.append("# Edit people.json and run _test/fixtures/regenerate.sh — do not edit this file.")
    out.append("# Sourced by provision-fixture.sh inside the running Samba DC.")
    out.append("")
    out.append("set -euo pipefail")
    out.append("")
    out.append(f"DOMAIN_DN={_sh_quote(base)}")
    out.append(f"USERS_DN={_sh_quote(users_dn)}")
    out.append(f"LDB={_sh_quote(ldb)}")
    out.append("")

    # ---- groups ----
    out.append("# ----- groups ----------------------------------------------------------------")
    for g in groups:
        out.append(f"samba-tool group add {_sh_quote(g['name'])} >/dev/null")
    out.append("")
    out.append("# ----- nested-group memberships ----------------------------------------------")
    has_nesting = False
    for g in groups:
        for inner in g.get("memberGroups", []):
            has_nesting = True
            out.append(
                f"samba-tool group addmembers {_sh_quote(g['name'])} "
                f"{_sh_quote(inner)} >/dev/null"
            )
    if not has_nesting:
        out.append("# (none)")
    out.append("")

    # ---- named users ----
    out.append("# ----- named users -----------------------------------------------------------")
    out.append("create_user() {")
    out.append("    local sam=\"$1\" given=\"$2\" surname=\"$3\" mail=\"$4\" password=\"$5\"")
    out.append("    samba-tool user create \"$sam\" \"$password\" \\")
    out.append("        --given-name=\"$given\" \\")
    out.append("        --surname=\"$surname\" \\")
    out.append("        --mail-address=\"$mail\" \\")
    out.append("        --use-username-as-cn \\")
    out.append("        >/dev/null")
    out.append("    # set displayName so ADClient::entry2User picks up the right 'name'")
    out.append("    ldbmodify -H \"$LDB\" >/dev/null <<EOF")
    out.append("dn: CN=${sam},${USERS_DN}")
    out.append("changetype: modify")
    out.append("replace: displayName")
    out.append("displayName: ${given} ${surname}")
    out.append("EOF")
    out.append("}")
    out.append("")
    out.append("set_attr() {")
    out.append("    local sam=\"$1\" attr=\"$2\" value=\"$3\"")
    out.append("    ldbmodify -H \"$LDB\" >/dev/null <<EOF")
    out.append("dn: CN=${sam},${USERS_DN}")
    out.append("changetype: modify")
    out.append("replace: ${attr}")
    out.append("${attr}: ${value}")
    out.append("EOF")
    out.append("}")
    out.append("")
    for u in users:
        out.append(
            f"create_user {_sh_quote(u['uid'])} {_sh_quote(u['givenName'])} "
            f"{_sh_quote(u['sn'])} {_sh_quote(u['mail'])} {_sh_quote(u['password'])}"
        )
        if "mobile" in u:
            out.append(
                f"set_attr {_sh_quote(u['uid'])} mobile {_sh_quote(u['mobile'])}"
            )
        if "ad_userAccountControl" in u:
            out.append(
                f"set_attr {_sh_quote(u['uid'])} userAccountControl "
                f"{_sh_quote(u['ad_userAccountControl'])}"
            )
    out.append("")

    # ---- named-user → group memberships ----
    out.append("# ----- named-user → group memberships ---------------------------------------")
    members_by_group = {g["name"]: [] for g in groups}
    for u in users:
        for g in u.get("memberOf", []):
            if g in members_by_group:
                members_by_group[g].append(u["uid"])
    for gname, uids in members_by_group.items():
        if uids:
            joined = ",".join(uids)
            out.append(
                f"samba-tool group addmembers {_sh_quote(gname)} "
                f"{_sh_quote(joined)} >/dev/null"
            )
    out.append("")

    # ---- padding users ----
    if padding:
        out.append("# ----- padding users so count assertions pass --------------------------------")
        out.append("echo \"Creating padding users (this takes a minute)...\"")
        out.append(f"PADDING_PASS={_sh_quote(padding['password'])}")
        out.append(f"PADDING_SN={_sh_quote(padding['sn'])}")
        out.append(f"for i in $(seq 1 {padding['count']}); do")
        uid_fmt = padding["uid_format"].replace("{i:03d}", "%03d").replace("{i}", "%d")
        given_fmt = padding["givenName_format"].replace("{i}", "%d")
        out.append(f"    sam=$(printf '{uid_fmt}' \"$i\")")
        out.append(f"    given=$(printf '{given_fmt}' \"$i\")")
        out.append("    samba-tool user create \"$sam\" \"$PADDING_PASS\" \\")
        out.append("        --given-name=\"$given\" \\")
        out.append("        --surname=\"$PADDING_SN\" \\")
        out.append("        --use-username-as-cn \\")
        out.append("        >/dev/null")
        for m in padding.get("memberships", []):
            out.append(f"    if [ \"$i\" -le {m['first_n']} ]; then")
            out.append(
                f"        samba-tool group addmembers {_sh_quote(m['group'])} "
                f"\"$sam\" >/dev/null"
            )
            out.append("    fi")
        out.append("done")
        out.append("")
    return "\n".join(out)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--target", required=True, choices=["openldap", "samba"])
    args = p.parse_args()

    spec = load_spec()
    if args.target == "openldap":
        sys.stdout.write(render_openldap(spec))
    else:
        sys.stdout.write(render_samba(spec))


if __name__ == "__main__":
    main()
