name: Tests for AD

on: [push, pull_request]

jobs:
    testAD:
        name: PHP ${{ matrix.php-versions }} DokuWiki ${{ matrix.dokuwiki-branch }}
        runs-on: macos-10.15
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

        strategy:
            matrix:
                php-versions: ['7.4']
                dokuwiki-branch: [ 'master']
            fail-fast: false

        steps:
            - name: Cache Vagrant boxes
              uses: actions/cache@v2
              with:
                path: ~/.vagrant.d/boxes
                key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
                restore-keys: |
                    ${{ runner.os }}-vagrant-

            - name: Install AD
              run: |
                  wget https://github.com/splitbrain/vagrant-active-directory/archive/refs/heads/master.zip
                  unzip master.zip
                  rm master.zip
                  cd vagrant-active-directory-master
                  vagrant up
                  cd ..

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, intl, PDO, pdo_sqlite, bz2

            - name: Setup problem matchers
              run: |
                echo ::add-matcher::${{ runner.tool_cache }}/php.json
                echo ::add-matcher::${{ runner.tool_cache }}/phpunit.json

            - name: Download DokuWiki Test-setup
              run: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

            - name: Run DokuWiki Test-setup
              env:
                  CI_SERVER: 1
                  DOKUWIKI: ${{ matrix.dokuwiki-branch }}
              run: sh travis.sh

            - name: Setup PHPUnit
              run: |
                  php _test/fetchphpunit.php
                  cd _test

            - name: Run PHPUnit
              run: |
                cd _test
                php phpunit.phar --verbose --stderr --group plugin_pureldap
