name: Tests for AD

on: [push, pull_request]

jobs:
    testAD:
        name: PHP ${{ matrix.php-versions }} DokuWiki ${{ matrix.dokuwiki-branch }}
        runs-on: windows-latest
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

        strategy:
            matrix:
                php-versions: ['7.4']
                dokuwiki-branch: [ 'master']
            fail-fast: false

        steps:
            - name: Install AD
              run: |
                  C:\msys64\usr\bin\wget.exe https://github.com/splitbrain/vagrant-active-directory/archive/refs/heads/master.zip
                  unzip master.zip
                  Remove-Item master.zip
                  cd vagrant-active-directory-master
                  .\scripts\install_ad.ps1
                  .\scripts\configure_ad.ps1 'example.local' 'EXAMPLE' 'Admin123#'
                  .\scripts\certificate.ps1 'dc' 'example.local' 'C:'
                  Start-Service NTDS -Verbose
                  Restart-Service -Name CertPropSvc,CryptSvc,DNS,ADWS,NTDS -Verbose
                  Get-ADDomain
                  cd ..
                  Remove-Item vagrant-active-directory-master -Recurse

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, intl, PDO, pdo_sqlite, bz2

            - name: Setup problem matchers
              run: |
                echo ::add-matcher::${{ runner.tool_cache }}/php.json
                echo ::add-matcher::${{ runner.tool_cache }}/phpunit.json

            - name: Download DokuWiki Test-setup
              run: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

            - name: Run DokuWiki Test-setup
              env:
                  CI_SERVER: 1
                  DOKUWIKI: ${{ matrix.dokuwiki-branch }}
              run: sh travis.sh

            - name: Setup PHPUnit
              run: |
                  php _test/fetchphpunit.php
                  cd _test

            - name: Run PHPUnit
              run: |
                cd _test
                php phpunit.phar --verbose --stderr --group plugin_pureldap
